WeSale/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("userauths.routes")),
    path("", include("core.routes")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/routes.py
from django.urls import path, include
from core import views


app_name = "core"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("welcome/", views.index, name="index"),
    # category
    path("category/", views.category_list_view, name="category-list"),
    path("category/<cid>/", views.category_product_view, name="category-product-list"),
    # vendor
    path("vendors/", views.vendor_list_view, name="vendor-list"),
    path("product-detail/<pk>/", views.product_detail_view, name="details"),
    # search
    path("search/", views.search_view, name="search"),
    # path("recommend/<pk>/", views.recommend_view, name="recommend"),
    path("your-products/", views.vendor_products, name="your-products"),
    path("add-products/", views.add_product, name="add-product"),
    # filtr products
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    path("cart/", views.cart_items, name="cart"),
    path("delete-from-cart/", views.delete_cart_item, name="delete-from-cart"),
    # Adding Reviews
    path("ajax-add-review/<pk>", views.add_review_form, name="ajax-add-review"),
    # Checkout
    path("checkout/", views.checkout_view, name="checkout"),
    # paypal url
    path("paypal/", include("paypal.standard.ipn.urls")),
    # payment successful
    path("payment-completed/", views.payment_completed_view, name="payment_completed"),
    # payment failed
    path("payment-failed/", views.payment_failed_view, name="payment_failed"),
]

userauths/routes.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.sign_up, name="register"),
    path("sign-in/", views.sign_in, name="login"),
    path("sign-out/", views.logout_view, name="logout"),
    path("update_profile/", views.create_vendor, name="update-profile"),
    path("vendor_profile/", views.success_view, name="profile"),
    path("vendor_profile/", views.customer_profile, name="customer-profile"),
]

templates/partials/base.html
{% load static %} {% load custom_filter %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0" />
    <title>CraftersHub</title>

    {% include 'styles/css.html' %}
    <link
      rel="stylesheet"
      href="{% static
    'output/style.css' %}"
    />
    <script src="{% static 'JQUERY/jquery.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  </head>
  <body class="bg-[#f7f7f7] min-h-screen font-sans">
    <header class="w-full static">
      <nav class="text-right space-x-5 p-4 flex justify-between items-center">
        <div>
          <form action="{% url 'core:search' %}" method="GET">
            <input
              class="w-[150px] h-[30px] border-2 border-gray-400 rounded-md p-4"
              type="text"
              placeholder="Search Product"
              aria-placeholder="search products"
              style="text-align: center"
              name="q"
            />
            <button
              class="bg-teal-500 px-4 rounded-md shadow-xl text-gray-100"
              type="submit"
            >
              Search
            </button>
          </form>
        </div>

        <div class="font-medium text-teal-400 space-x-5">
          <a href="{% url 'core:cart' %}"
            >Cart
            <span
              class="bg-green-500 w-6 text-white rounded-full p-2 cart-items-count"
              >{{ request.session.cart_data_obj| length}}</span
            >
          </a>
          <a
            href="{% if user.is_authenticated %}{% if user.role == 'vendor' %}{% url 'userauths:profile' %}{% else %} {% url 'userauths:customer-profile' %}{% endif %}{% else %}{% url 'userauths:logout' %}{% endif %}"
            >Account</a
          >
          <a href="{% url 'userauths:logout' %}">Logout</a>
        </div>
      </nav>
      <nav
        class="text-left py-3 pl-16 space-x-5 text-slate-100 bg-teal-500 w-full font-medium"
      >
        <a
          ><button
            class="hover:text-yellow-400 hover:underline transition hover:-translate-y-2 hover:translate-x-1 duration-100 ease-out"
          >
            Hot Deals
          </button></a
        >
        <a href="{% url 'core:index' %}"
          ><button
            class="hover:text-yellow-400 hover:underline transition hover:-translate-y-2 hover:translate-x-1 duration-100 ease-out"
          >
            Home
          </button></a
        >
        <a href="{% url 'core:category-list' %}"
          ><button
            class="hover:text-yellow-400 hover:underline transition hover:-translate-y-2 hover:translate-x-1 duration-100 ease-out"
          >
            Categories
          </button></a
        >
        <a
          ><button
            class="hover:text-yellow-400 hover:underline transition hover:-translate-y-2 hover:translate-x-1 duration-100 ease-out"
          >
            Shop
          </button></a
        >
        <a href="{% url 'core:vendor-list' %}"
          ><button
            class="hover:text-yellow-400 hover:underline transition hover:-translate-y-2 hover:translate-x-1 duration-100 ease-out"
          >
            Vendors
          </button></a
        >
      </nav>
      {% if messages %} {% for message in messages %}

      <div
        id="notify"
        class="w-[90%] h-8 flex items-center my-2 ml-2 p-5 rounded-md bg-cyan-500/40 border-[1px] border-gray-700/40 {{message.tags}}"
      >
        {{message}}
      </div>

      {% endfor %} {% endif %}
    </header>

    {% block content %} {% endblock %}
    <script>
      document
        //buton functionality in the product detail page
        .getElementById("descriptionBtn")
        .addEventListener("click", function () {
          document.getElementById("reviews").style.display = "none";
          document.getElementById("specification").style.display = "none";
          document.getElementById("description").style.display = "block";
          descriptionBtn.classList.add("text-green-700");
          descriptionBtn.classList.remove("text-gray-700");
          reviewsBtn.classList.add("text-gray-700");
          reviewsBtn.classList.remove("text-green-700");
          specificationBtn.classList.add("text-gray-700");
          specificationBtn.classList.remove("text-green-700");
        });

      document
        .getElementById("reviewsBtn")
        .addEventListener("click", function () {
          document.getElementById("description").style.display = "none";
          document.getElementById("specification").style.display = "none";
          document.getElementById("reviews").style.display = "block";
          reviewsBtn.classList.add("text-green-700");
          reviewsBtn.classList.remove("text-gray-700");
          descriptionBtn.classList.add("text-gray-700");
          descriptionBtn.classList.remove("text-green-700");
          specificationBtn.classList.add("text-gray-700");
          specificationBtn.classList.remove("text-green-700");
        });
      document
        .getElementById("specificationBtn")
        .addEventListener("click", function () {
          document.getElementById("reviews").style.display = "none";
          document.getElementById("specification").style.display = "block";
          document.getElementById("description").style.display = "none";
          specificationBtn.classList.add("text-green-700");
          specificationBtn.classList.remove("text-gray-700");
          descriptionBtn.classList.remove("text-green-700");
          descriptionBtn.classList.add("text-gray-700");
          reviewsBtn.classList.add("text-gray-700");
          reviewsBtn.classList.remove("text-green-700");
        });
    </script>
    <script>
      // Get a reference to the div
      var myDiv = document.getElementById("notify");

      // Use setTimeout to hide the div after 2000 milliseconds (2 seconds)
      setTimeout(function () {
        myDiv.style.display = "none";
      }, 1000);
    </script>
    <script src="{% static 'js/function.js' %}"></script>
  </body>
</html>

templates/partials/pre.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CraftersHub</title>
    {% include 'styles/css.html' %}
    <link
      rel="stylesheet"
      href="{% static
    'output/style.css' %}"
    />
  </head>
  <body class="bg-[#f7f7f7] min-h-screen font-sans w-full">
    <header class="w-full">
      <nav
        class="flex justify-between items-center mr-10 p-5 text-teal-600 font-semibold"
      >
        <a>CraftersHub</a>
        <!--<div class="space-x-5">
          <a href="{% url "userauths:register" %}">SignUp</a>
        </div> -->
      </nav>
      {% if messages %} {% for message in messages %}

      <div
        id="notify"
        class="w-[90%] h-8 flex items-center my-2 ml-2 p-5 rounded-md bg-red-500/50 border-[1px] border-gray-700/40 {{message.tags}}"
      >
        {{message}}
      </div>

      {% endfor %} {% endif %}
    </header>
    {% block content%} {% endblock %}

    <script>
      // Get a reference to the div
      var myDiv = document.getElementById("notify");

      // Use setTimeout to hide the div after 2000 milliseconds (2 seconds)
      setTimeout(function () {
        myDiv.style.display = "none";
      }, 1000);
    </script>
  </body>
</html>