WeSale/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("userauths.routes")),
    path("", include("core.routes")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from core.models import Product, Category, ProductReview


class ProductForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "style": "padding:10px; border-width:1px; border-color:gray; width:250px; border-radius:7px;",
                "placeholder": "Product Title",
            }
        )
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        widget=forms.Select(
            attrs={
                "style": "padding:10px; border-width:1px; border-color:gray; width:250px; border-radius:7px;",
                "placeholder": "Category",
            }
        ),
    )

    image = forms.ImageField()

    price = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "style": "padding:10px; border-width:1px; border-color:gray; width:250px; border-radius:7px;",
                "placeholder": "Price",
            }
        )
    )
    description = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "style": "padding:10px; border-width:1px; border-color:gray; width:250px; border-radius:7px;",
                "placeholder": "Product Description",
            }
        )
    )
    specifications = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "style": "padding:10px; border-width:1px; border-color:gray; width:250px; border-radius:7px;",
                "placeholder": "Product details/specifics ",
            }
        )
    )
    product_status = forms.ChoiceField(
        choices=Product.STATUS,
        required=True,
        widget=forms.Select(attrs={"class": "styled-choice-field"}),
    )

    class Meta:
        model = Product
        fields = [
            "title",
            "category",
            "image",
            "price",
            "description",
            "specifications",
            "product_status",
        ]


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(
        widget=forms.Textarea(attrs={"placeholder": "Write a review"})
    )

    class Meta:
        model = ProductReview
        fields = ["review", "rating"]

core/routes.py
from django.urls import path, include
from core import views


app_name = "core"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("welcome/", views.index, name="index"),
    # category
    path("category/", views.category_list_view, name="category-list"),
    path("category/<cid>/", views.category_product_view, name="category-product-list"),
    # vendor
    path("vendors/", views.vendor_list_view, name="vendor-list"),
    path("product-detail/<pk>/", views.product_detail_view, name="details"),
    # search
    path("search/", views.search_view, name="search"),
    # path("recommend/<pk>/", views.recommend_view, name="recommend"),
    path("your-products/", views.vendor_products, name="your-products"),
    path("add-products/", views.add_product, name="add-product"),
    # filtr products
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    path("cart/", views.cart_items, name="cart"),
    path("delete-from-cart/", views.delete_cart_item, name="delete-from-cart"),
    # Adding Reviews
    path("ajax-add-review/<pk>", views.add_review_form, name="ajax-add-review"),
    # Checkout
    path("checkout/", views.checkout_view, name="checkout"),
    # paypal url
    path("paypal/", include("paypal.standard.ipn.urls")),
    # payment successful
    path("payment-completed/", views.payment_completed_view, name="payment_completed"),
    # payment failed
    path("payment-failed/", views.payment_failed_view, name="payment_failed"),
]

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from core.forms import ProductForm, ProductReviewForm
from django.contrib import messages
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.db.models import Avg

from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm

# from core.recommender import ContentBasedRecommender


# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import linear_kernel

# Create your views here.from django.shortcuts import render
from core.models import (
    ProductImages,
    Product,
    CartOrder,
    Address,
    Vendor,
    ProductReview,
    Category,
    CartOrderItems,
    Wishlist,
)


# Create your views here.
def index(request):
    """
    This function returns the index page with all products.
    """
    popular = Product.objects.filter(product_status="popular")

    products = Product.objects.all()

    home = Product.objects.filter(category="3", product_status="in_stock")

    paint = Product.objects.filter(category="5", product_status="in_stock")

    furniture = Product.objects.filter(category="4", product_status="in_stock")

    women = Product.objects.filter(category="6", product_status="in_stock")

    # flash = Product.objects.latest()

    context = {
        "popular": popular,
        "products": products,
        "home": home,
        "furniture": furniture,
        "women": women,
        "paint": paint,
    }
    return render(request, "core/index.html", context)


def home_view(request):
    """
    This function returns the index page with all products.
    """
    popular = Product.objects.filter(product_status="popular")

    products = Product.objects.all()

    # flash = Product.objects.latest()

    context = {
        "popular": popular,
        "products": products,
    }
    return render(request, "core/homepage.html", context)


def category_list_view(request):
    """
    This function returns the list of categories.
    """
    category = Category.objects.all()

    context = {"Category": category}

    return render(request, "core/category.html", context)


def category_product_view(request, cid):
    """
    This function returns the list of products in a specific category.
    """
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(category=category)

    context = {"category": category, "products": products}

    return render(request, "core/category-product-list.html", context)

    context = {"products": products}
    return render(request, "core/index.html", context)


def category_list_view(request):
    category = Category.objects.all()

    context = {"Category": category}

    return render(request, "core/category.html", context)


def product_detail_view(request, pk):
    product = Product.objects.get(pk=pk)

    # getting all product reviews
    reviews = ProductReview.objects.filter(product=product).order_by("-date")

    # Average ratings for specific product
    average_rating = ProductReview.objects.filter(product=product).aggregate(
        rating=Avg("rating")
    )

    # product review_form
    review_form = ProductReviewForm()

    context = {
        "product": product,
        "reviews": reviews,
        "average_rating": average_rating,
        "review_form": review_form,
    }

    return render(request, "core/product_detail.html", context)


def vendor_list_view(request):
    vendors = Vendor.objects.all()

    context = {
        "vendors": vendors,
    }

    return render(request, "core/vendor-list.html", context)


def search_view(request):
    query = request.GET.get("q")
    # key = Product.objects.get(pk=pk)

    products = Product.objects.filter(title__icontains=query)

    context = {
        "products": products,
        "query": query,
    }
    return render(request, "core/search.html", context)


@login_required
def add_product(request):
    vendor = Vendor.objects.get(user=request.user)
    categories = Category.objects.all()

    if request.method == "POST":
        product_form = ProductForm(request.POST, request.FILES)

        if product_form.is_valid():
            # Retrieve or create the Category instance
            category_name = product_form.cleaned_data["category"]
            category, created = Category.objects.get_or_create(title=category_name)

            # Create a new Product instance with the associated Category
            Product.objects.create(
                title=product_form.cleaned_data["title"],
                description=product_form.cleaned_data["description"],
                price=product_form.cleaned_data["price"],
                specifications=product_form.cleaned_data["specifications"],
                image=product_form.cleaned_data["image"],
                product_status=product_form.cleaned_data["product_status"],
                category=category,
                vendor=vendor,
                user=request.user,
            )
        messages.success(request, "Product added successfully")
        return redirect("userauths:profile")
    else:
        product_form = ProductForm()

    return render(
        request,
        "core/add_product.html",
        {"product_form": product_form, "categories": categories},
    )


@login_required
def vendor_products(request):
    user = request.user
    vendor = Vendor.objects.get(user=user)

    products = Product.objects.filter(vendor=vendor)

    context = {"user": user, "vendor": vendor, "products": products}

    return render(request, "core/view_products.html", context)


def add_to_cart(request):
    cart_product = {}
    cart_product[str(request.GET["id"])] = {
        "title": request.GET["title"],
        "qty": request.GET["qty"],
        "image": request.GET["image"],
        "price": request.GET["price"],
        "pid": request.GET["pid"],
    }
    if "cart_data_obj" in request.session:
        if str(request.GET["id"]) in request.session["cart_data_obj"]:
            cart_data = request.session["cart_data_obj"]
            cart_data[str(request.GET["id"])]["qty"] = int(
                cart_product[str(request.GET["id"])]["qty"]
            )
            cart_data.update(cart_data)
            request.session["cart_data_obj"] = cart_data
        else:
            cart_data = request.session["cart_data_obj"]
            cart_data.update(cart_product)
            request.session["cart_data_obj"] = cart_data
    else:
        request.session["cart_data_obj"] = cart_product

    return JsonResponse(
        {
            "data": request.session["cart_data_obj"],
            "totalcartitems": len(request.session["cart_data_obj"]),
        }
    )


def cart_items(request):

    cart_total_amount = 0

    if "cart_data_obj" in request.session:
        for p_id, item in request.session["cart_data_obj"].items():
            cart_total_amount += int(item["qty"]) * float(item["price"])

        return render(
            request,
            "core/cart.html",
            {
                "cart_data": request.session["cart_data_obj"],
                "totalcartitems": len(request.session["cart_data_obj"]),
                "cart_total_amount": cart_total_amount,
            },
        )
    else:
        messages.warning(request, "Your cart is Empty")
        return redirect("core:index")


def delete_cart_item(request):
    product_id = str(request.GET["id"])

    if "cart_data_obj" in request.session:
        if product_id in request.session["cart_data_obj"]:
            cart_data = request.session["cart_data_obj"]
            del request.session["cart_data_obj"][product_id]
            request.session["cart_data_obj"] = cart_data

    cart_total_amount = 0

    if "cart_data_obj" in request.session:
        for p_id, item in request.session["cart_data_obj"].items():
            cart_total_amount += int(item["qty"]) * float(item["price"])

    context = render_to_string(
        "core/async/cart-list.html",
        {
            "cart_data": request.session["cart_data_obj"],
            "totalcartitems": len(request.session["cart_data_obj"]),
            "cart_total_amount": cart_total_amount,
        },
    )
    return JsonResponse(
        {"data": context, "totalcartitems": len(request.session["cart_data_obj"])}
    )


def add_review_form(request, pk):
    product = Product.objects.get(pk=pk)
    user = request.user

    review = ProductReview.objects.create(
        user=user,
        product=product,
        review=request.POST["review"],
        rating=request.POST["rating"],
    )
    context = {
        "user": user.username,
        "review": request.POST["review"],
        "rating": request.POST["rating"],
    }
    average_reviews = ProductReview.objects.filter(product=product).aggregate(
        rating=Avg("rating")
    )

    return JsonResponse(
        {
            "bool": True,
            "context": context,
            "average_review": average_reviews,
        }
    )


@login_required
def checkout_view(request):
    host = request.get_host()
    paypal_dict = {
        "business": settings.PAYPAL_RECEIVER_EMAIL,
        "amount": "200",
        "item_name": "Order-item-15",
        "invoice": "INVOICE 15",
        "currency_code": "USD",
        "return_url": "https://{}{}".format(host, reverse("core:payment_completed")),
        "cancel_url": "https://{}{}".format(host, reverse("core:payment_failed")),
    }


userauths/routes.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.sign_up, name="register"),
    path("sign-in/", views.sign_in, name="login"),
    path("sign-out/", views.logout_view, name="logout"),
    path("update_profile/", views.create_vendor, name="update-profile"),
    path("vendor_profile/", views.success_view, name="profile"),
    path("vendor_profile/", views.customer_profile, name="customer-profile"),
]

templates/core/add-to-cart.html
<div>add to cart</div>

templates/core/add_product.html
{% extends "partials/base.html" %} {% block content %}
<section>
  <!-- add_product.html -->
  <div
    id="addProductModal"
    class="fixed inset-0 bg-black bg-opacity-50 justify-center items-center"
  >
    <div class="bg-white p-6 rounded shadow-lg">
      <h2 class="text-2xl font-semibold mb-4">Add New Product</h2>
      <form
        method="POST"
        enctype="multipart/form-data"
        class="grid grid-cols-2 space-y-5 ml-5"
      >
        {% csrf_token %}
        <div>
          <label class="pt-5" for="{{product_form.category.id_for_label}}"
            >Category:</label
          >
          <div>{{product_form.category}}</div>
        </div>
        <div>
          <label class="pb-5">Add Product Image</label>

          <div>{{product_form.image}}</div>
        </div>
        <div>{{product_form.title}}</div>
        <div>{{product_form.description}}</div>
        <div>{{product_form.price}}</div>
        <div>{{product_form.specifications}}</div>

        <div>{{product_form.product_status}}</div>

        <button
          type="submit"
          class="bg-blue-500 text-white px-4 py-2 rounded w-44"
        >
          Add Product
        </button>

        <a
          href="{% url 'userauths:profile' %}"
          class="bg-blue-500 text-white px-4 py-2 rounded mt-10 w-20 text-center"
        >
          Back</a
        >
      </form>
    </div>
  </div>
</section>

{% endblock %}

templates/core/cart.html
{% extends "partials/base.html" %}{% load custom_filter %} {% block content %}

<main id="cart-list">
  <div class="container mx-auto py-10 text-gray-700">
    <h1 class="text-3xl font-bold mb-4">Shopping Cart</h1>
    <table class="w-3/4 border border-gray-300">
      <thead>
        <tr class="bg-green-500 text-gray-600">
          <th class="border border-gray-300 py-2 px-5"></th>
          <th class="border border-gray-300 px-5 py-2">Product</th>

          <th class="border border-gray-300 py-2 px-5">Price(Kshs)</th>
          <th class="border border-gray-300 py-2 px-5">Quantity</th>
          <th class="border border-gray-300 py-2 px-5">Sub Total(Kshs)</th>
          <th class="px-5">Remove</th>
        </tr>
      </thead>
      <tbody>
        {% for product_id, item in cart_data.items %}
        <tr class="text-center">
          <td class="border border-gray-300 px-5 py-2 flex justify-center">
            <img
              class="w-24 h-24 object-cover shadow-xl border-2 border-cyan-200/40 rounded-xl"
              src="{{ item.image }}"
              alt="#"
            />
          </td>
          <td class="border border-gray-300 py-1 px-5">{{ item.title }}</td>
          <td class="border border-gray-300 py-2 px-5">{{ item.price }}</td>
          <td class="border border-gray-300 py-2 px-5">{{ item.qty }}</td>
          <td class="border border-gray-300 py-2 px-5">
            {{ item.price|multiply:item.qty }}
          </td>
          <td>
            <button
              class="bg-green-500 text-white px-4 py-1 rounded delete-product"
              data-product="{{product_id}}"
            >
              Delete
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <p class="mt-4 font-medium">Total Price: Ksh {{ cart_total_amount }}</p>
    <div class="my-10">
      <a
        href="{% url 'core:checkout' %}"
        class="bg-indigo-500 text-white py-2 px-4 rounded-md hover:bg-indigo-600"
      >
        Checkout
      </a>
    </div>
  </div>
</main>

{% endblock %}

templates/core/category-product-list.html
{% extends 'partials/base.html' %} {% block content %}

<main>
  <section>
    <div class="bg-white w-full mt-5 rounded-lg">
      <h2
        class="bg-amber-600 p-10 rounded-t-md text-gray-100 font-semibold text-2xl"
      >
        {{category.title}}
      </h2>

      <div class="p-3">
        <p>
          We found
          <strong>{{products.count}}</strong> item{{products.count|pluralize}}
          for you!
        </p>
      </div>

      <div class="grid grid-cols-3">
        {% for p in products %}
        <div
          class="bg-gray-50 w-40 h-40 flex flex-col justify-center items-center my-5 mx-5 p-4 shadow-xl border rounded-lg"
        >
          <img class="w-24 h-24 object-cover" src="{{p.image.url}}" />
          <p>{{p.title}}</p>
        </div>

        {% endfor %}
      </div>
    </div>
  </section>
</main>

{% endblock %}

templates/core/checkout.html
{% extends 'partials/base.html' %} {% block content %}
<main>
  <div class="container mx-auto py-12">
    <div class="max-w-md mx-auto bg-white p-8 border rounded-md shadow-md">
      <h2 class="text-2xl font-semibold mb-6">Checkout</h2>
      <div class="my-10">
        <a
          href="{% url 'core:cart' %}"
          class="bg-indigo-500 text-white py-2 px-4 rounded-md hover:bg-indigo-600"
        >
          Go back to Cart
        </a>
      </div>
      <!-- Shipping Information -->
      <div class="mb-6">
        <h3 class="text-lg font-semibold mb-2">Shipping Information</h3>
        <form>
          <div class="mb-4">
            <label for="name" class="block text-sm font-medium text-gray-700"
              >Name</label
            >
            <input
              type="text"
              id="name"
              name="name"
              class="mt-1 p-1 block w-full shadow-sm sm:text-sm border border-gray-500 rounded-md"
            />
            <label for="address" class="block text-sm font-medium text-gray-700"
              >Address</label
            >
            <input
              type="text"
              id="address"
              name="address"
              class="mt-1 p-1 block w-full shadow-sm sm:text-sm border border-gray-500 rounded-md"
            />
            <label for="City" class="block text-sm font-medium text-gray-700"
              >City</label
            >
            <input
              type="text"
              id="city
              name="
              city
              class="mt-1 p-1 block w-full shadow-sm sm:text-sm border border-gray-500 rounded-md"
            />
            <label for="Phone" class="block text-sm font-medium text-gray-700"
              >Phone Number</label
            >
            <input
              type="text"
              id="phone"
              name="phone"
              class="mt-1 p-1 block w-full shadow-sm sm:text-sm border border-gray-500 rounded-md"
            />
          </div>
          <!-- Other fields (address, city, state, zip code, etc.) -->
        </form>
      </div>
      <!-- Order Summary -->
      <div>
        <h3 class="text-lg font-semibold mb-2">Order Summary</h3>

        <!-- Sample Cart Items (Replace with dynamic data) -->
        <div class="grid grid-cols-3 space-x-5 mb-2">
          <table class="w-3/4 border border-gray-300">
            <thead>
              <tr class="text-gray-600">
                <th class="border border-gray-300 px-5 py-2">Product</th>

                <th class="border border-gray-300 py-2 px-5">Price(Kshs)</th>
                <th class="border border-gray-300 py-2 px-5">Quantity</th>
              </tr>
            </thead>
            <tbody>
              {% for product_id, item in cart_data.items %}
              <tr class="text-center">
                <td class="border border-gray-300 py-1 px-5">
                  {{ item.title }}
                </td>
                <td class="border border-gray-300 py-2 px-5">
                  {{ item.price }}
                </td>
                <td class="border border-gray-300 py-2 px-5">{{ item.qty }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

        <!-- Total -->
        <div class="flex justify-between font-semibold">
          <div>Total</div>
          <div>{{ cart_total_amount|floatformat }}</div>
        </div>
      </div>
      <div class="text-blue-600">
        <h2>Pay with:</h2>
       <!-- <input type="radio" />
        <p>Cash on Delivery</p>

        <input type="radio" />
        <p>Paypal</p>
      </div>
      <!-- Checkout Button -->
      <div class="mt-6">
        <button
          class="bg-indigo-500 text-white py-2 px-4 rounded-md hover:bg-indigo-600"
        >
          {{paypal_payment_button.render}}
        </button>
      </div>
    </div>
  </div>
</main>

{% endblock %}

templates/core/index.html
{% extends 'partials/base.html' %} {% block content %}

<main>
  <section class="flex gap-10 pr-2">
    <nav class="bg-teal-500 text-gray-100 mt-5 w-52 p-5">
      <div class="flex flex-col space-y-5">
        <a href="{% url 'core:category-list' %}">Browse all Categories</a>
        <hr />
        <a href="{% url 'core:index' %}">Home</a>
        <hr />
        <a>About</a>
        <hr />
        <a>Shop</a>
        <hr />
        <a>Vendors</a>
      </div>
    </nav>

    <div class="bg-white w-full mt-5 rounded-lg">
      <h2
        class="bg-amber-600 p-3 rounded-t-md text-gray-100 font-semibold text-xl"
      >
        Popular Products
      </h2>

      <div class="grid grid-cols-3">
        {% for p in popular %}
        <button>
          <a href="{% url 'core:details' p.pk %}">
            <div
              class="bg-gray-50 w-40 h-48 flex flex-col justify-center items-center my-5 mx-5 p-4 shadow-xl border rounded-lg text-gray-600"
            >
              <img class="w-24 h-24 object-cover" src="{{p.image.url}}" />
              <p class="text-center">{{p.title}}</p>
              <p>{{p.price}}</p>
            </div>
          </a>
        </button>

        {% endfor %}
      </div>
    </div>
  </section>

  <section class="mr-2">
    <div class="bg-white w-full mt-5 rounded-lg">
      <h2
        class="bg-gray-900 p-3 rounded-t-md text-gray-100 font-semibold text-xl"
      >
        Home Decors
      </h2>

      <div class="grid grid-cols-4">
        {% for h in home %}
        <button>
          <a href="{% url 'core:details' h.pk %}">
            <div
              class="bg-gray-50 w-40 h-48 text-gray-600 flex flex-col justify-center items-center my-5 mx-5 p-4 shadow-xl border rounded-lg"
            >
              <img class="w-24 h-24 object-cover" src="{{h.image.url}}" />
              <p class="text-center">{{h.title}}</p>
              <p>{{h.price}}</p>
            </div>
          </a>
        </button>

        {% endfor %}
      </div>
    </div>
  </section>

  <section class="mr-2">
    <div class="bg-white w-full mt-5 rounded-lg">
      <h2
        class="bg-teal-500 p-3 rounded-t-md text-gray-100 font-semibold text-xl"
      >
        Furniture
      </h2>

      <div class="grid grid-cols-4">
        {% for f in furniture %}
        <button>
          <a href="{% url 'core:details' f.pk %}">
            <div
              class="bg-gray-50 w-40 h-48 text-gray-600 flex flex-col justify-center items-center my-5 mx-5 p-4 shadow-xl border rounded-lg"
            >
              <img class="w-24 h-24 object-cover" src="{{f.image.url}}" />
              <p class="text-center">{{f.title}}</p>
              <p>{{f.price}}</p>
            </div>
          </a>
        </button>

        {% endfor %}
      </div>
    </div>
  </section>

  <section class="mr-2">
    <div class="bg-white w-full mt-5 rounded-lg">
      <h2
        class="bg-gray-900 p-3 rounded-t-md text-gray-100 font-semibold text-xl"
      >
        For Women
      </h2>

      <div class="grid grid-cols-4">
        {% for w in women %}
        <button>
          <a href="{% url 'core:details' w.pk %}">
            <div
              class="bg-gray-50 w-40 h-48 text-gray-600 flex flex-col justify-center items-center my-5 mx-5 p-4 shadow-xl border rounded-lg"
            >
              <img class="w-24 h-24 object-cover" src="{{w.image.url}}" />
              <p class="text-center">{{w.title}}</p>
              <p>{{w.price}}</p>
            </div>
          </a>
        </button>

        {% endfor %}
      </div>
    </div>
  </section>

  <section class="mr-2">
    <div class="bg-white w-full mt-5 rounded-lg">
      <h2
        class="bg-gray-900 p-3 rounded-t-md text-gray-100 font-semibold text-xl"
      >
        Custom Wall Paints
      </h2>

      <div class="grid grid-cols-4">
        {% for c in paint %}
        <button>
          <a href="{% url 'core:details' c.pk %}">
            <div
              class="bg-gray-50 w-40 h-48 text-gray-600 flex flex-col justify-center items-center my-5 mx-5 p-4 shadow-xl border rounded-lg"
            >
              <img class="w-24 h-24 object-cover" src="{{c.image.url}}" />
              <p class="text-center">{{c.title}}</p>
              <p>{{c.price}}</p>
            </div>
          </a>
        </button>

        {% endfor %}
      </div>
    </div>
  </section>
</main>

{% endblock %}

templates/core/product_detail.html
{% extends "partials/base.html" %} {% block content %}

<main class="my-10 mx-5 text-gray-500">
  <div class="w-auto h-auto p-5 flex space-x-6">
    <figure
      class="w-64 h-64 flex justify-between items-center shadow-xl rounded-md"
    >
      <img
        class="w-60 h-60 mx-5 object-cover product-image"
        src="{{product.image.url}}"
      />
    </figure>
    <div class="flex flex-col space-y-5">
      <p class="text-3xl">{{product.title}}</p>
      <p class="text-2xl text-emerald-500 product-price">{{product.price}}</p>

      <input
        type="hidden"
        class="product-pid"
        value="{{product.pid}}"
        name=""
        id=""
      />
      <input
        type="hidden"
        class="product-title"
        value="{{product.title}}"
        name=""
        id=""
      />
      <input
        id="product-quantity"
        class="border-2 border-gray-400 p-3 w-28"
        type="number"
        value="1"
        min="1"
        placeholder="Quantity"
      />
      <button
        type="submit"
        class="w-28 h-12 p-1 bg-green-600 text-white rounded-md"
        id="add-to-cart-btn"
      >
        <i class="fi-rs-shopping-cart"></i>
        Add to Cart
      </button>
    </div>
  </div>

  <section class="flex">
    <div class="container w-2/3 mt-5 p-5 border border-gray-400">
      <div class="flex gap-10">
        <button
          class="border border-gray-400 px-2 py-1 rounded-xl font-medium"
          id="descriptionBtn"
        >
          Description
        </button>
        <button
          class="border border-gray-400 px-2 py-1 rounded-xl font-medium"
          id="specificationBtn"
        >
          Specification
        </button>
        <button
          class="border border-gray-400 px-2 py-1 rounded-xl font-medium"
          id="reviewsBtn"
        >
          Reviews ({{reviews.count}})
        </button>
      </div>
      <div class="mt-2 ml-5">
        <div id="description">
          <p>{{product.description}}</p>
        </div>
        <div id="specification" class="hidden">
          <p>{{product.specifications}}.</p>
        </div>

        <div id="reviews" class="hidden">
          {% for r in reviews %}
          <div class="pb-5 comment-list">
            <div class="flex">
              <a class="text-green-500 font-semibold py-2"
                >{{r.user.username|title}} |<span class="text-black font-light">
                  {{r.date|date}}</span
                ></a
              >
              {% for s in r.rating|ljust:r.rating %}
              <p class="px-1 mt-2 text-yellow-500 text-md">★</p>
              {% endfor %}
            </div>
            <div class="w-[500px]">
              <hr />
            </div>
            <p>{{r.review}}</p>
          </div>
          {% endfor %}
          <div>
            <strong class="text-green-600 italic" id="review-res"></strong>
            <form
              class="flex flex-col space-y-2 comment-form hide-comment-form"
              id="CommentForm"
              method="POST"
              action="{% url 'core:ajax-add-review' product.pid %}"
            >
              {% csrf_token %} {{review_form}}
              <button
                type="submit"
                id="CommentForm"
                class="bg-green-600 w-20 text-white p-2 rounded-md"
              >
                Submit
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-5 pl-2 w-auto font-medium text-black">
      <h2>Average Star Rating</h2>

      <p>
        <span class="px-2 text-yellow-500">★★★★★</span
        >{{average_rating.rating|floatformat}} of 5
      </p>
    </div>
  </section>
</main>
{% endblock %}